### ISSUE TITLE
streamline what is tidyverse section

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/advanced-tidyverse-lesson#1]
add some formatting, reduce redunancy

**Comment by reblake** [comment]
Agreed.  I'd suggest finding another thing besides "stability" that base R excels at/is known for.  Makes everything else seem unstable.

**Comment by qdread** [comment]
Although I do think stability is a huge plus for base R.... so definitely should be kept as a positive for that.

Also my impression was that the word "concision" is a little too formal. I probably would have used conciseness. See the great debate resolver stackexchange: https://english.stackexchange.com/questions/114505/concision-vs-conciseness
