### ISSUE TITLE
tidy eval section

### ISSUE THREAD

**Issue by reblake** [SESYNC-ci/advanced-tidyverse-lesson#14]
If you're going to use the term "data masking" you need to define it.  That particular term is not something I'm familiar with, but I of course know the concept.  You could probably just remove "via data masking".  Or, alternately, provide a link out "to learn more about tidy eval and underlying concepts see.."

You also say in your first bullet point that you don't have to refer to a dataframe name, which strictly isn't true.  You still have to supply a dataframe to work with (even if piped).  I think rewording a bunch of this will improve it.  

Also need to edit text to better link/flow into next section...lay out the why of what you're doing.

**Comment by reblake** [comment]
Also, it would be nice to actually do something in this section that demonstrates tidy eval.  I understand you're just setting up the next section on renaming columns, but before that an example would be great.

**Comment by qdread** [comment]
Yeah I think these are good points, especially the one about data masking since it isn't a term I'd heard either. It seems like you would not really need to know it unless you plan to do tidyverse programming.

**Comment by khondula** [comment]
links for tidy eval added to summary; corrected and reworded data masking def based on language in dplyr vignette; added a little transition for the focus on variable names. code completion in rstudio undermines the point of the connection being made... admit its a stretch but imo not really enough to warrant a note in the lesson.
example with mutate/rename for one column given as example of data masking, then tidy select is in exercise

**Comment by khondula** [comment]
rename is actually tidy select not data masking. point out data masking via mutate with mdy function later
