### ISSUE TITLE
Explanation of fs functions

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/advanced-tidyverse-lesson#19]
I think it would be nice to say more specifically up front what the `fs` package does, as well as possibly saying generally what the three example functions do rather than just providing an example of their output. I don't know those functions but maybe they have other arguments people might want to know besides their defaults?

**Comment by khondula** [comment]
also this is wrong as written. path_dir etc functions work on non fs_path character vectors, [tidy fs_paths](https://fs.r-lib.org/index.html#tidy-paths) are more just about `/` characters and color formatting.

**Comment by khondula** [comment]
the fs functions are pretty straightforward and dont have extra arguments. Nothing interesting enough to really get into, removed those functions and include link in exercise.
