### ISSUE TITLE
load lubridate package

### ISSUE THREAD

**Issue by reblake** [SESYNC-ci/advanced-tidyverse-lesson#23]
code chunk that loads lubridate has not made it to the worksheet (even though it appears to on the scrolly page)

**Comment by khondula** [comment]
might be because this throws an error so it didnt like rebuilding that slide... either way, need to fix ca lines 52 in worksheet to make sure it lines up with slides

**Comment by khondula** [comment]
had eval = FALSE

**Comment by khondula** [comment]
updated worksheet but still need to ensure changes to lesson chunks worked proper
