### ISSUE TITLE
give a little more info about penguins data

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/advanced-tidyverse-lesson#3]
one or two sentences about whats in the data set, credit LTER

**Comment by reblake** [comment]
Rather than saying the fs package is "non-core tidyverse", you might want to say loaded as dependency with tidyverse() package.  Above this you mention it's loaded as a dependency.  As currently worded, it might indicate it would have to be loaded manually.

**Comment by reblake** [comment]
At the end of the penguins section, you say you want to read in using read_csv(), but then you don't do it.  You need to provide some explanation/justification in this section as to why you have to move on to the mapping section that's next.    Something along the lines of...We want to iterate over our 50 files to read each one in, so ...   That will lead nicely into the next section

**Comment by khondula** [comment]
Taking out "non-core tidyverse" to reduce confusion, but need to keep in library(fs) because it doesn't load with the 8 core tidyverse packages. Will rearrange read csv with col types stuff to go before map as per #21
