### ISSUE TITLE
add description of piped workflow

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/advanced-tidyverse-lesson#5]
perhaps redundant but maybe nice review to explain all parts of 

```
pg_df <- dir_ls("data/penguins") %>%
  map_df(~read_csv(.x), .id = "filename")
```

**Comment by reblake** [comment]
I like how you describe pipes as a core tenet of the tidyverse.  Are there a few other core tenets plus this one that you could put up at the top of the lesson and then refer to during the lesson to tie things together?
