### ISSUE TITLE
pattern replacement heading

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/advanced-tidyverse-lesson#6]
seems to be in the wrong place flow-wise

**Comment by reblake** [comment]
Likewise, I don't think "Glue" should be a heading.  Rather I suggest all headings describe what you want to do.  So for glue section, it would be "Combine column contents", or something like that.

**Comment by reblake** [comment]
Reminder to flesh out the text describing what's going on in this section.  Seems like notes still.
