### ISSUE TITLE
date string manipulation

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/advanced-tidyverse-lesson#7]

**Comment by khondula** [comment]
also the regex is incorrect since data now live nested inside the penguins folder. add in /penguins/

**Comment by reblake** [comment]
You might consider putting the as_date() stuff in the worksheet, not the console.  

Also want to explain that mdy() is a function and what that function does. 

Also need to explain the date specifications:  %B %d %Y

**Comment by khondula** [comment]
turns out mdy function also works on the full string, don't need to even extract from the rest of the filepath! 

So, show hard way first - extract relevant characters from string, as_date with specific format, helpers to guess. then show mdy

**Comment by khondula** [comment]
also need to explain | in str remove all
